version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: test-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: currency_exchange
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: